### ISSUE TITLE
Server crashes on startup when attempting to use this mod on a dedicated server

### ISSUE THREAD

**Issue by NJL5390** [FionaTheMortal/Better-Biome-Blend#1]
Minecraft Version: 1.16.5
Forge Version: 36.0.42
Better Biome Blend: 0.1.3

Whenever I attempt to use this mod on a dedicated server, the server crashes on startup. I know I probably don't need to have this mod on a server at all, but this mod seems to give a considerable performance boost to my game and I like to have consistency between servers and clients to ensure they both run well. 

So could you at least make it so that the server doesn't crash when I use the mod on a server?

Thanks for the awesome mod!

Crash Report: https://pastebin.com/qv1HT7ye
Latest Log: https://pastebin.com/CeCDWqkV

**Comment by FionaTheMortal** [comment]
Fixed! Version 0.1.4 is available on curseforge.
