### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by MaxBr5** [FionaTheMortal/better-biome-blend#10]
<pre>Dear Fiona The Mortal,
1.17 is already out and fabric is already available
on 1.17, please update it for 1.17 . The fabric wiki
has already updated for 1.17 not that long ago and I
like little block goats and axolotls.
Yours sincerely,
MaxBr5</pre>

**Comment by MaxBr5** [comment]
<pre>Forge is taking far too long to update to 1.17 but it does
not mean that you can’t update it for fabric 1.17 .</pre>

**Comment by FionaTheMortal** [comment]
It's out now and I got to deal with some fabric weirdness

**Comment by MaxBr5** [comment]
Thank you.
