### ISSUE TITLE
1.12 - crash on startup

### ISSUE THREAD

**Issue by xemnes** [FionaTheMortal/better-biome-blend#11]
hello, just tried out this mod, and found out it causes the game to crash before the game window loads

there was no crash report generated so heres my latest log:
https://pastebin.com/g7RUg687

**Comment by BrisingrAerowing** [comment]
You have the wrong Mixin version loaded. Try using [Mixin 0.7-0.8 Compat](https://www.curseforge.com/minecraft/mc-mods/mixin-0-7-0-8-compatibility)

**Comment by FionaTheMortal** [comment]
Thanks for the bug report and pointer. I don't know if there is much I can do to fix this. 1.12 Mixin seems to be less comptabile and updating the mixin version my mod uses caused other modpacks to crash.

**Comment by MaxBr5** [comment]
Actually, that is not Fiona the Mortal's fault, it is the forge team's fault for not embedding it.

**Comment by xemnes** [comment]
using that mixin mod linked solved the problem, thanks.

**Comment by MaxBr5** [comment]
<pre>You can blame the forge team.</pre>
