### ISSUE TITLE
[Forge 1.16.5] Compatability with Serene Seasons

### ISSUE THREAD

**Issue by Liamdude** [FionaTheMortal/Better-Biome-Blend#25]
This message relates to #6 because the coloring issue with Serene Seasons may have returned. The first screenshot is with BBB and the second is without BBB. For some reason, Serene Seasons is not applying its seasonal changes with BBB installed. This was reproduced on a minimal mod list: LazyDFU to speed loading, Optifine G8, BBB, and Serene Seasons.

EDIT: I just did some more testing, and it would appear that while BBB is installed, the textures will not change immediately when a season changes. Instead, you have to leave the world and then rejoin for the full changes to take effect. This is not necessary when BBB is absent.

Forge version: 36.2.0
Serene Seasons version: 1.16.5-4.0.1.120-universal
Better Biome Blend version: 1.16.4-1.2.3-forge

[
![2021-07-29_00 50 47](https://user-images.githubusercontent.com/41766967/127433907-b2e8fad6-73ca-4ee0-9b8c-c2c6769fe566.png)
![2021-07-29_00 52 15](https://user-images.githubusercontent.com/41766967/127433918-2d4ab37b-6bed-4871-8ff8-01d676c91c0a.png)
](url)

**Comment by FionaTheMortal** [comment]
Ah yes you see I'm actually not smart

**Comment by FionaTheMortal** [comment]
I caused this in the recent updates. Thank you for reporting. I'll be releasing a fix shortly. Until then use the 1.1.x versions. They should be fine.

**Comment by FionaTheMortal** [comment]
1.2.4 fixes the issue. Thank you for doing additional testing, that made it very easy for me to know what went wrong.
