### ISSUE TITLE
1.18 port

### ISSUE THREAD

**Issue by MaxBr5** [FionaTheMortal/Better-Biome-Blend#27]
<pre>1.18 experimental snapshots are out and I and many others
would like to play with the beautiful new mountains and lush caves
with the beauty of Fiona the Mortal's better biome blend. Fabric
has already been ported so this will not be that hard.</pre>

**Comment by MaxBr5** [comment]
<pre>Fiona the mortal's better biome blend crashes on 1.18!</pre>

**Comment by FionaTheMortal** [comment]
well I'm really not a fan of messing around with java build system magic so when I tried setting up the project in 1.18 and it didn't work I gave up because my god can I not be bothered to deal with gradle

**Comment by MaxBr5** [comment]
<pre>I know some gradle build system update magic
If use windows, open dos/cmd and run
gradlew wrapper --gradle-version=7.3-20210807021145+0000

else, in a terminal emualator, run
bash gradlew wrapper --gradle-version=7.3-20210807021145+0000

That will update to gradle 7.3, which may work with 1.18
experimental snapshots but I don't know. I haven't tried.</pre>

**Comment by MaxBr5** [comment]
<pre>Tell me if it works!</pre>
