### ISSUE TITLE
[1.12] Unable to load the mod due to "duplicate mod"

### ISSUE THREAD

**Issue by Vapaman** [FionaTheMortal/Better-Biome-Blend#30]
When trying to open the version 1.1.6 with forge 14.23.5.2855 forge detects a duplicate instance of the mod and refuses to load further:
![kuva](https://user-images.githubusercontent.com/77460466/134824652-76ae65d1-a72d-42d1-bf1e-333cef53f31d.png)
Here is some logs if they help:
[debug.log](https://github.com/FionaTheMortal/better-biome-blend/files/7232282/debug.log)
[latest.log](https://github.com/FionaTheMortal/better-biome-blend/files/7232283/latest.log)
Tried it with and without mixin compatibility, same results on each one.

**Comment by Vapaman** [comment]
This issue is present even when loading the mod just on its own

**Comment by FionaTheMortal** [comment]
Thank you for reporting. I will have to look into it when I have more free time for moddev.

**Comment by FionaTheMortal** [comment]
I'm unable to reproduce the issue. Have you tried using a different launcher?

**Comment by NLBlacky** [comment]
I'm having the same issue, as have many other player that reported this in my community + Discord from the modpack Ocean Outlast. [Here is my latest log](https://pastebin.com/CwfMdXP3). Weird thing is, the modpack worked fine for me for weeks, and then all of the sudden I got this error again. 

I've confirmed that there is no duplicated mod inside the Mods folder. Issue seems to be with the mod itself. Perhaps the INIT is called twice or something? I'm using GDLauncher, but I believe many of the others that told me they had the same issue were using different launchers.

![image](https://user-images.githubusercontent.com/42154364/141696269-b869231a-5d04-46d3-bfef-f3adf5e05d42.png)

![image](https://user-images.githubusercontent.com/42154364/141696278-0fd87d82-c3dd-4117-9313-f01e1f8ee722.png)

![image](https://user-images.githubusercontent.com/42154364/141696293-8cb85f45-a7c8-4190-8d3e-912d9ced3865.png)

**Comment by juraj-hrivnak** [comment]
Look into the `mods/1.12.2` or `mods/memory_repo` folder. Maybe it's also there for some reason.

**Comment by NLBlacky** [comment]
> Look into the `mods/1.12.2` or `mods/memory_repo` folder. Maybe it's also there for some reason.

As I mentioned in my post, I checked the entire mods folder, which included all sub folders and a search function. There are no duplicates mods.

**Comment by FionaTheMortal** [comment]
Fixed version will be up soon
