### ISSUE TITLE
Incompatibility with Xaero's World Map mod (1.12.2)

### ISSUE THREAD

**Issue by jahirtrap** [FionaTheMortal/better-biome-blend#31]
Apparently when I use a better biome blend together with the world map, the colors of the birch and fir leaves are shown in gray, this only happens in 1.12.2, in newer versions everything is correct.
![2021-10-08_10 53 55](https://user-images.githubusercontent.com/75038202/136588000-3b6fa877-39ed-489f-82bf-a1f216e52181.png)

**Comment by FionaTheMortal** [comment]
They fixed it on their end :]
