### ISSUE TITLE
Biome Blend Resets To 5x5

### ISSUE THREAD

**Issue by OneunderK** [FionaTheMortal/Better-Biome-Blend#32]
Each time I try to increase the blend from 5x5 (Default), it doesn't save the change despite appearing to re-render. This is on both Optifine (on Fabric through OptiFabric) and Sodium (through Iris Shaders' fork of Sodium).  I have tried this with a setup containing only other visual/sound mods, and with only a shader and one of the aforementioned renderers. Also, at the end of the slider beyond 29x29 it resets to 5x5.

**Comment by FionaTheMortal** [comment]
Do you have a minimap mod installed?

**Comment by FionaTheMortal** [comment]
Please check if the setting also resets if BBB is not installed. Closing this for now.
