### ISSUE TITLE
[1.16.5] Incompatibility with FTB Chunks

### ISSUE THREAD

**Issue by Bereim** [FionaTheMortal/Better-Biome-Blend#33]
https://i.imgur.com/uYYTG9P.jpg
When using FTB Chunks with Better Biome Blend, the map shows discolored borders on some generated chunks, but doesn't seem to affect initial spawn area.
[Link to FTB Issue](https://github.com/FTBTeam/FTB-Mods-Issues/issues/109)

**Comment by FionaTheMortal** [comment]
Not able to reproduce this at all. Is this still an issue?

**Comment by Bereim** [comment]
No, seems to be fixed in the latest version of FTB Chunks.
