### ISSUE TITLE
Can we expect a 1.18 release?

### ISSUE THREAD

**Issue by respectablenoob-source** [FionaTheMortal/Better-Biome-Blend#35]

**Comment by FionaTheMortal** [comment]
Ofc when I find the time

**Comment by MaxBr5** [comment]
The axolotls are begging for you to do it and so do the floating islanders.

**Comment by MaxBr5** [comment]
Can I do some build system magic?

**Comment by FionaTheMortal** [comment]
The port is going to be non-trivial because biomes are now 3D so it'll take some time

**Comment by MaxBr5** [comment]
Also, check the pull requests bit for I added java 17 compatibility.
