### ISSUE TITLE
Crash on latest version when clicking 'video settings' from main menu

### ISSUE THREAD

**Issue by Jes7ix** [FionaTheMortal/Better-Biome-Blend#51]
Description: mouseClicked event handler

java.lang.VerifyError: Bad type on operand stack

Full crashlog attached

[crash-2022-01-18_01.00.20-client.txt](https://github.com/FionaTheMortal/better-biome-blend/files/7885397/crash-2022-01-18_01.00.20-client.txt)

**Comment by FionaTheMortal** [comment]
seems to be optiFINE doing smth

**Comment by FionaTheMortal** [comment]
Fixed
