### ISSUE TITLE
[1.12.2] Incompatibility with JourneyMap mod

### ISSUE THREAD

**Issue by SomeNameUsername** [FionaTheMortal/Better-Biome-Blend#53]
Water shows up as white on minimap and fullscreen map when both Better Biome Blend and JourneyMap are installed

![2022-03-11_01 58 10](https://user-images.githubusercontent.com/96031181/157781554-d85b97de-9b98-4647-a329-4d597845b7ec.png)
![2022-03-11_01 58 14](https://user-images.githubusercontent.com/96031181/157781562-2681b0bf-cc10-4287-abb7-c85e094b8dd5.png)

**Comment by FionaTheMortal** [comment]
cement :]
