### ISSUE TITLE
[Sodium compatibility idea]make it overide sodium's biome blending.

### ISSUE THREAD

**Issue by MaxBr5** [FionaTheMortal/Better-Biome-Blend#54]
Perhaps adding an override like what you did with optifine will make it work with sodium.

**Comment by Scarlaid** [comment]
Isn't this mod already compatible with [this version of Sodium](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.18.2-0.4.1)?

**Comment by StartsMercury** [comment]
It is still open on their side [CaffeineMC/sodium-fabric#647](https://github.com/CaffeineMC/sodium-fabric/issues/647). (Unless they forgot to close it?!?)

**Comment by StartsMercury** [comment]
Maybe I'll test something, then edit this comment...

> Maybe in `config/sodium-mixin.properties`
> ```properties
> # previous properties
> features.fast_biome_colors = false
> # next properties
> ```

**Comment by FionaTheMortal** [comment]
I finally got around to it. Added compatibility here:

0ac4ecce85a0a8670187596ac12adf65dbcab537
4a6cdc802c88ed8e4d7e76260c6503a86efbae0e

At least now _a_ compatible version exists until they decide to change their code.
It seems to work pretty well for now.

**Comment by Kasualix** [comment]
Is it possible for you to backport the compatibility to 1.16.5?
