### ISSUE TITLE
Create button issue

### ISSUE THREAD

**Issue by StockiesLad** [FionaTheMortal/Better-Biome-Blend#55]
The create config button doesnt show when betterbiomeblend is present.
https://gist.github.com/FluffyBumblebees/bdd948b647907364d3145d66d06650ae
BBB: 1.3.5
Create fabric 0.4.1+build.589

**Comment by FionaTheMortal** [comment]
It's probably the code right here breaking assumtions in Create code

https://github.com/FionaTheMortal/better-biome-blend/blob/0ac4ecce85a0a8670187596ac12adf65dbcab537/src/main/java/fionathemortal/betterbiomeblend/BetterBiomeBlendClient.java#L190

I can probably change that to only change the tooltip now that option isn't being used anymore anyway.

Never mind has nothing to do with it

**Comment by StockiesLad** [comment]
Sounds good. Thank you for the fast response

**Comment by FionaTheMortal** [comment]
I disabled most parts of BBB and it was still happening so I think it must be something on their end.

**Comment by StockiesLad** [comment]
Oh ok. I'll be sure to relay this information back to them.
