### ISSUE TITLE
Modrinth not up to date

### ISSUE THREAD

**Issue by triphora** [FionaTheMortal/Better-Biome-Blend#58]
I noticed that the [Modrinth releases](https://modrinth.com/mod/better-biome-blend) aren't up-to-date with the [CurseForge releases](https://curseforge.com/project/446253) (specifically in regards to 1.19). Could you keep the Modrinth releases up to date?

If you'd like, you can even set up [Minotaur](https://github.com/modrinth/minotaur) or [mc-publish](https://github.com/Kir-Antipov/mc-publish) to automate build publishing.

**Comment by FionaTheMortal** [comment]
thanks :]
