### ISSUE TITLE
[Forge 1.16.5] Serene season's foliage colours don't work when Better Biome Blend is installed

### ISSUE THREAD

**Issue by NJL5390** [FionaTheMortal/Better-Biome-Blend#6]
Better Biome Blend version: 1.1.3-forge
Serene Seasons version: 4.0.1.91
Forge Version: 36.1.2
Minecraft Version: 1.16.5
Latest Log: https://pastebin.com/cSXSjfwe

Hello! I noticed when using your mod alongside Serene seasons that the foliage and grass colour changes that serene seasons does to each biome depending on the season don't work. 

Here are some screenshots to show what I mean:

Winter Season Without Better Biome Blend:
![2021-03-25_11 45 07](https://user-images.githubusercontent.com/64381954/112469033-e4353080-8d60-11eb-937c-26673bb58e82.png)

Winter Season With Better Biome Blend:
![2021-03-25_11 42 31](https://user-images.githubusercontent.com/64381954/112469172-1050b180-8d61-11eb-9c0d-6f2d1b03aea8.png)
It appears that your mod is preventing serene seasons from changing the foliage and grass colours with each season, which makes there seem to be very little difference between each season.

**Comment by FionaTheMortal** [comment]
Thank you for your bug report. I will have to look into it.

**Comment by FionaTheMortal** [comment]
Has been fixed an will be part of the next release.

**Comment by NJL5390** [comment]
Awesome! Thanks a lot!
