### ISSUE TITLE
1.12.2 Configuring Better Biome Blend with Optifine

### ISSUE THREAD

**Issue by KnightCa** [FionaTheMortal/Better-Biome-Blend#65]
Minecraft: Forge 1.12.2
Optifine: HD U G5
Better Biome Blend: 1.1.7

When going into the Details section of Video Settings, there is no apparent option for Biome Blend. The closest thing seems the on/off toggle for Smooth Biomes. 
![Settings1](https://user-images.githubusercontent.com/51968609/218214581-8f21c2b8-6513-4c25-bce8-06ef5a0d0f69.jpg)

The configuration for Better Biomes Blend is set at 14 and cant be changed through the GUI.
![Settings2](https://user-images.githubusercontent.com/51968609/218214579-acf3468b-07ab-4937-bc2f-2add750d15b4.jpg)

What's the best way to configure this mod, so it can use the 29x29 setting mentioned?

**Comment by FionaTheMortal** [comment]
Setting 14 is equivalent to 29x29. One is radius the other the diameter. If you want max setting then you already have that. IIRC you can configure it from the main menu. I think the reason for that was that I didn't want to figure out how to make all chunks redraw when the setting is changed. I don't think the 1.12 mod has any UI even without Optifine.
