### ISSUE TITLE
Please write a build script for jdk 16

### ISSUE THREAD

**Issue by MaxBr5** [FionaTheMortal/Better-Biome-Blend#9]
<pre>Dear Fiona the Mortal,
Please make a build script for jdk 16, I got an <a href="https://www.youtube.com/watch?v=kCGOjbyOlc4">example script<a>.
Yours Sincerely,
MaxBr5</pre>

**Comment by FionaTheMortal** [comment]
That looks way too complicated to be worth the effort.

**Comment by MaxBr5** [comment]
This is not the real thing, Just read the gradle docs or try maven.

**Comment by FionaTheMortal** [comment]
Is there any benefit to it? I might find the time for it *eventually*

**Comment by MaxBr5** [comment]
<pre>Yes! It is fun fixing things and gradle will not annoy me with a bunch of errors.</pre>
